[package]
name = "stack-overflow"
version = "0.1.0"
authors = ["Anders Conbere <anders@stripe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
